/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlyphsRouteImport } from './routes/glyphs'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as GlyphsIndexRouteImport } from './routes/glyphs.index'
import { Route as GlyphsTokenIdRouteImport } from './routes/glyphs.$tokenId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlyphsRoute = GlyphsRouteImport.update({
  id: '/glyphs',
  path: '/glyphs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GlyphsIndexRoute = GlyphsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlyphsRoute,
} as any)
const GlyphsTokenIdRoute = GlyphsTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => GlyphsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glyphs': typeof GlyphsRouteWithChildren
  '/studio': typeof StudioRoute
  '/world': typeof WorldRoute
  '/api/media': typeof ApiMediaRoute
  '/glyphs/$tokenId': typeof GlyphsTokenIdRoute
  '/glyphs/': typeof GlyphsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/world': typeof WorldRoute
  '/api/media': typeof ApiMediaRoute
  '/glyphs/$tokenId': typeof GlyphsTokenIdRoute
  '/glyphs': typeof GlyphsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glyphs': typeof GlyphsRouteWithChildren
  '/studio': typeof StudioRoute
  '/world': typeof WorldRoute
  '/api/media': typeof ApiMediaRoute
  '/glyphs/$tokenId': typeof GlyphsTokenIdRoute
  '/glyphs/': typeof GlyphsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glyphs'
    | '/studio'
    | '/world'
    | '/api/media'
    | '/glyphs/$tokenId'
    | '/glyphs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/world' | '/api/media' | '/glyphs/$tokenId' | '/glyphs'
  id:
    | '__root__'
    | '/'
    | '/glyphs'
    | '/studio'
    | '/world'
    | '/api/media'
    | '/glyphs/$tokenId'
    | '/glyphs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlyphsRoute: typeof GlyphsRouteWithChildren
  StudioRoute: typeof StudioRoute
  WorldRoute: typeof WorldRoute
  ApiMediaRoute: typeof ApiMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glyphs': {
      id: '/glyphs'
      path: '/glyphs'
      fullPath: '/glyphs'
      preLoaderRoute: typeof GlyphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glyphs/': {
      id: '/glyphs/'
      path: '/'
      fullPath: '/glyphs/'
      preLoaderRoute: typeof GlyphsIndexRouteImport
      parentRoute: typeof GlyphsRoute
    }
    '/glyphs/$tokenId': {
      id: '/glyphs/$tokenId'
      path: '/$tokenId'
      fullPath: '/glyphs/$tokenId'
      preLoaderRoute: typeof GlyphsTokenIdRouteImport
      parentRoute: typeof GlyphsRoute
    }
  }
}

interface GlyphsRouteChildren {
  GlyphsTokenIdRoute: typeof GlyphsTokenIdRoute
  GlyphsIndexRoute: typeof GlyphsIndexRoute
}

const GlyphsRouteChildren: GlyphsRouteChildren = {
  GlyphsTokenIdRoute: GlyphsTokenIdRoute,
  GlyphsIndexRoute: GlyphsIndexRoute,
}

const GlyphsRouteWithChildren =
  GlyphsRoute._addFileChildren(GlyphsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlyphsRoute: GlyphsRouteWithChildren,
  StudioRoute: StudioRoute,
  WorldRoute: WorldRoute,
  ApiMediaRoute: ApiMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
